---
- name: Remove running web application
  become: yes
  docker_compose:
    project_src: .
    state: absent

- name: Start web application
  become: yes
  docker_compose:
    project_src: .
    state: present
    build: yes
    recreate: always
    remove_orphans: yes
  register: results