FROM python:3.7

COPY harvest /app/harvest
COPY script /app/script

WORKDIR /app/harvest

RUN pip install mpi4py

RUN pip install -r requirements.txt

WORKDIR /app/script

CMD ["bash","./harvest_instance3_two_cores.sh"]