---
version: '3'

services:
  
  web-backend:
    container_name: web-backend
    build: 
      context: .
      dockerfile: Dockerfile.backend
    command: python manage.py runserver 0.0.0.0:5000
    ports:
      - "5000:5000" 

  web-frontend:
    container_name: web-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    stdin_open: true
    ports: 
      - "3000:3000"
    depends_on:
      - web-backend
    networks:
      - lognet
      
networks:
  lognet:
    driver: bridge
