FROM python:3.7

COPY ./harvest /app/harvest
COPY ./script /app/script

WORKDIR /app/harvest

RUN sudo apt update

RUN pip install mpi4py

RUN pip install -r requirements.txt

WORKDIR /app/script

CMD ["bash","./harvest_instance1_two_cores.sh"]