---
version: '3'

services:
  
  web-backend:
    container_name: web-backend
    build: 
      context: .
      dockerfile: Dockerfile.backend
    command: python manage.py runserver 0.0.0.0:8000
    expose: 
      - "8000"
    ports:
      - "8000:8000" 

  web-frontend:
    container_name: web-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    stdin_open: true
    expose: 
      - "3000"
    ports: 
      - "3000:3000"
    links:
      - web-backend
