availability_zone: melbourne-qh2-uom
network: qh2-uom-internal

volumes:
  - vol_name: db-cluster-1
    vol_size: 80
  - vol_name: db-cluster-2
    vol_size: 80
  - vol_name: db-cluster-3
    vol_size: 80
  - vol_name: app
    vol_size: 10

security_groups:
  - name: group45_ssh
    description: "Security group for SSH access for group45"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 172.0.0.0/0
  - name: group45_http
    description: "Security group for HTTP for group45"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0