---
# Pull couchDB in Database Instances
- name: Pull couchDB image 
  become: yes  
  docker_image:
    name: "{{ couchdb_image }}"
    source: pull

# Remove couchDB in Database Instances
- name: Remove old couchDB containers
  become: yes
  docker_container:
    name: "{{ couchdb_name }}"
    state: absent

- name: Reboot machines
  become: yes
  reboot:
    reboot_timeout: 3000

# Create couchDB in Database Instances
- name: Create couchDB containers
  become: yes
  docker_container:
    name: "{{ couchdb_name }}"
    env:
        COUCHDB_USER: "{{ couchdb_user_name }}"
        COUCHDB_PASSWORD: "{{ couchdb_password }}"
        NODENAME: "{{ ansible_default_ipv4.address }}"
        COUCHDB_SECRET: "{{ couchdb_secret }}"
    volumes: 
      - "/data/couchdb:/opt/couchdb/data"
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100:9100"
    image: "{{ couchdb_image }}"
    detach: yes
    state: started

# Modifying vm.args to make the machine run
- name: Modify vm.args to set cookie
  become: yes
  command: docker exec {{ couchdb_name }} bash -c "echo \"-setcookie {{ couchdb_cookie }}\" >> /opt/couchdb/etc/vm.args" 
  
# Restarting couchDB containers with update files
- name: Restart couchDB containers
  become: yes
  docker_container:
    name: "{{ couchdb_name }}"
    state: started
    restart: yes

# Binding 0.0.0.0 for each cluster node
- name: Bind address to 0.0.0.0
  command: "curl -X PUT http://{{couchdb_user_name}}:{{couchdb_password}}@127.0.0.1:5984/_node/_local/_config/chttpd/bind_address -d '\"0.0.0.0\"'"

# Setting up UUID for each cluster node
- name: Setting up UUID
  command: "curl -X PUT http://{{couchdb_user_name}}:{{couchdb_password}}@127.0.0.1:5984/_node/_local/_config/couchdb/uuid -d '\"{{couchdb_uuid}}\"'"

# Setting up the value for the secret
- name: Setting up http secret
  command: "curl -X PUT http://{{couchdb_user_name}}:{{couchdb_password}}@127.0.0.1:5984/_node/_local/_config/couch_httpd_auth/secret -d '\"{{couchdb_secret}}\"'"

