---
# Create remote security group
- name: Create a remote security group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ remote_security_groups }}'

# Create remote security group rules
- name: Create remote security group rules
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_group: '{{ item.remote_group }}'
    state: present
  loop: '{{ remote_security_groups }}'

# Add remote security group to instance
- name: Add security group to instance
  os_server:
    name: '{{ item.name }}'
    image: '{{ instance_image }}'
    key_name: '{{ instance_key_name }}'
    flavor: '{{ instance_flavor }}'
    availability_zone: '{{ availability_zone }}'
    network: '{{ network }}'
    security_groups:
      - group45_tcp_connections
      - group45_ssh
      - group45_http
    timeout: 600
    state: present
  loop: '{{ instances }}'