# Definition of Constants
CMD_LINE_DEFINED_ARGUMENTS = "ha:f:"
HELP_ARGUMENT = "-h"
AUTHEN_CONFIG_ARGUMENT = "-a"
FILTER_CONFIG_ARGUMENT = "-f"

JSON_API_KEY_PROP = "api_key"
JSON_API_SECRET_KEY_PROP = "api_secret_key"
JSON_ACCESS_TOKEN_PROP = "access_token"
JSON_ACCESS_TOKEN_SECRET = "access_token_secret"

JSON_STREAMING_SECTION_PROP = "streaming"
JSON_SEARCHING_SECTION_PROP = "searching"
JSON_POLITICIANS_PROP = "politicians"
JSON_PROCESSOR_PROP = "processor"
JSON_AUTHEN_PROP = "authen"
JSON_LOCATIONS_PROP = "locations"
JSON_LANGUAGES_PROP = "languages"
JSON_TRACK_PROP = "track"
JSON_USERS_PROP = "users"

LIMIT_COUNT_PER_REQ = 200;
TWEET_MODE = "extended"

ONE_SECOND = 1
TWO_SECONDS = 2
ONE_MINUTE = 60

GEO = "geo"
PLACE = "place"
COORDINATES = "coordinates"
AUSTRALIA_COUNTRY_NAME = "australia"