---
  # Copy Directories to Database Instances
  - name: Copy harvest and script folder
    become: yes
    synchronize:
      src: "../../../{{ item }}"
      dest: /data/app
      mode: push
      rsync_opts:
        - "--exclude=dataset"
    with_items:
      - harvest
      - script
  
  # Install packages
  - name: Install pip modules
    become: yes
    pip:
      requirements: /data/app/harvest/requirements.txt
      state: present
  
  # Install openmpi packages
  - name: Install openmpi packages for mpi4py
    become: yes
    apt: 
      name: ['openmpi-bin', 'openmpi-common', 'openmpi-doc', 'libopenmpi-dev']
      state: latest
      install_recommends: yes
      update_cache: yes 
  
  # Install packages
  - name: Install mpi4py modules
    become: yes
    pip:
      name: mpi4py
      state: present
  
  # Run stream harvester
  - name: Execute harvest_instance1_two_cores.sh
    shell: bash harvest_instance1_two_cores.sh
    args:
      chdir: /data/app/script
    async: 1000
    poll: 0
    register: results

  - name: Testing the task
    async_status:
      jid: "{{ results.ansible_job_id }}"
    register: harvester_result
    until: harvester_result.finished
    retries: 10

  - debug: var=harvest_result.stdout_lines