---
# Copy Directories to Database Instances
- name: Copy harvest and script folder
  become: yes
  synchronize:
    src: "../../../{{ item }}"
    dest: /data/app
    mode: push
    rsync_opts:
      - "--exclude=dataset"
  with_items:
    - harvest
    - script

# Install packages
- name: Install pip modules
  become: yes
  pip:
    requirements: /data/app/harvest/requirements.txt
    state: present

# Run stream harvester
- name: Execute harvest_instance1_two_cores.sh
  become: yes
  command: ./harvest_instance1_two_cores.sh