---
# Remove harvesters in Database Instances
- name: Remove Harvest containers
  become: yes
  docker_container:
    name: "{{ harvester_instance1 }}"
    state: absent
    
# Copy Dockerfile to Database Instances
- name: Copy Dockerfile.harvest.stream
  become: yes
  copy:
    src: ../../templates/Dockerfile.harvest.stream
    dest: /home/ubuntu
    
# Copy Directories to Database Instances
- name: Copy harvest and script folder
  become: yes
  synchronize:
    src: "../../../{{ item }}"
    dest: /home/ubuntu
    mode: push
    rsync_opts:
      - "--exclude=dataset"
  with_items:
    - harvest
    - script

# Unzip data in harvest
#- name: Unzip dataset.tar.gz
#  become: yes
#  unarchive:
#    src: /home/ubuntu/harvest
#    dest: /home/ubuntu/harvest
#    remote_src: yes

# Create stream harvester 
- name: Build stream harvester image
  become: yes
  docker_image:
    name: "{{ harvester_instance1 }}"
    build: 
      dockerfile: "{{ dockerfile_stream }}"
      path: /home/ubuntu
      pull: yes
    state: present
    source: build
    
- name: Run stream harvester container
  become: yes
  docker_container:
    name: "{{ harvester_instance1 }}"
    volumes:
      - "/data/app:/app"
    image: "{{ harvester_instance1 }}"
    detach: yes
    state: started
    