---
- hosts: localhost
  vars_files:
    - host_vars/localhost.yaml
  gather_facts: true
  
  roles:
    - role: common
    - role: volume
    - role: security-group
    - role: instance

- hosts: allInstances
  vars_files:
    - host_vars/localhost.yaml
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/mayank-sharma-key.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no' 
  
  roles:
    - role: proxy
    - role: attach-volume
    - role: instance-environment
