---
- hosts: allInstances
  vars_files:
    - host_vars/remote.yaml
  gather_facts: true

  roles:
    - role: instance-environment

- hosts: slaveInstances
  vars_files:
    - host_vars/remote.yaml
  gather_facts: true

  roles: 
    - role: couchdb-slave

- hosts: masterInstances
  vars_files:
    - host_vars/remote.yaml
  gather_facts: true

  roles: 
    - role: couchdb-master

