---
# Adding proxies and mounting volumes to all instances
- hosts: allInstances
  vars_files:
    - host_vars/localhost.yaml
  gather_facts: true

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ./mayank-sharma-key.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no' 
  
  roles:
    - role: proxy
    - role: attach-volume

# Installing dependencies in all instances
- hosts: allInstances
  vars_files:
    - host_vars/remote.yaml
  gather_facts: true

  roles:
    - role: instance-environment

# Deploying couchdb in all db instances
- hosts: dbInstances
  vars_files:
    - host_vars/remote.yaml
  gather_facts: true

  roles: 
    - role: couchdb

# Configuring couchdb cluster using the master node
- hosts: masterInstance
  vars_files:
    - host_vars/remote.yaml
  gather_facts: true

  roles: 
   - role: couchdb-environment

