---
- name: Delete shards folder
  become: yes
  file:
    path: "/data/{{ item }}"
    state: absent
  with_items:
    - .delete
    - shards

- name: Delete shards folder
  become: yes
  file:
    path: "/data/{{ item }}"
    state: absent
  with_items:
    - _dbs.couch
    - _nodes.couch

- name: Uninstall old versions of docker
  become: yes
  apt:
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent

- name: Install dependencies
  become: yes
  apt:
    name: ['apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'software-properties-common', 'unzip', 'vim']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Add Docker apt repository key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository and update apt cache
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  become: yes
  pip:
    name: ['docker-compose']
    state: latest

- name: Create directory
  become: yes
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0777'

- name: Copy HTTP PROXY files
  become: yes
  copy:
    src: ../../templates/http-proxy.conf
    dest: /etc/systemd/system/docker.service.d/

- name: Create /.docker directory
  become: yes
  file:
    path: /home/ubuntu/.docker
    state: directory
    mode: '0777'

- name: Copy config.json files
  become: yes
  copy:
    src: ../../templates/config.json
    dest: /home/ubuntu/.docker

- name: Add user for docker
  become: yes
  user:
    name: "ubuntu"
    append: yes
    groups: docker

- name: Flush changes and restart Docker
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

