---
# Remove harvesters in Database Instances
- name: Remove Harvest containers
  become: yes
  docker_container:
    name: "{{ harvester_instance2 }}"
    state: absent

# Create search harvester 
- name: Build search harvester image
  become: yes
  docker_image:
    name: "{{ harvester_instance2 }}"
    build: 
     dockerfile: "{{ dockerfile_search }}"
     path: "../../templates/{{ dockerfile_search }}"
     pull: yes
    state: present
    source: build
    
