---
# Copy Directories to Database Instances
- name: Copy harvest and script folder
  become: yes
  synchronize:
    src: "../../../{{ item }}"
    dest: /data/app
    mode: push
    rsync_opts:
      - "--exclude=dataset"
  with_items:
    - harvest
    - script

# Install packages
- name: Install pip modules
  become: yes
  pip:
    requirements: /data/app/harvest/requirements.txt
    state: present

# Install openmpi packages
- name: Install openmpi packages for mpi4py
  become: yes
  apt: 
    name: ['openmpi-bin', 'openmpi-common', 'openmpi-doc', 'libopenmpi-dev']
    state: latest
    install_recommends: yes
    update_cache: yes 

# Install packages
- name: Install mpi4py modules
  become: yes
  pip:
    name: mpi4py
    state: present

# Change file permissions
#- name: making file executable
#  become: yes
#  file:
#    path: /data/app/script/harvest_instance1_two_cores.sh
#    mode: '0777'

# Run stream harvester
- name: Execute harvest_instance1_two_cores.sh
  command:
    chdir: /data/app/script
    cmd: bash harvest_instance1_two_cores.sh