---
# Install xfsprogs to format volumes
- name: Install xfsprogs
  become: yes
  apt:
    name: xfsprogs
    state: latest
    update_cache: yes

# Format volumes
- name: Format volume
  become: yes
  filesystem:
    fstype: xfs
    dev: "{{ item.device }}"
  when: item.device is defined
  loop: "{{ volumes }}"

# Checking the folders
- name: Checking and registering folders
  become: yes
  stat:
    path: "{{ item.mountpoint }}"
  register: directory_stats
  loop: "{{ volumes }}"

# Creating the directories in VM
- name: Create directory
  become: yes
  file:
    path: "{{ item.item.mountpoint }}"
    recurse: yes
    state: directory
  when: item.stat.exists == false
  loop: "{{ directory_stats.results }}"

# Mounting volumes to specific file paths
- name: Attach volume to instance
  become: yes
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.device }}"
    fstype: xfs
    state: mounted
  when: item.device is defined
  loop: "{{ volumes }}"
