---
- name: Format volume
  tags: 'volumes'
  become: yes
  filesystem:
    fstype: xfs
    dev: "{{ item.device }}"
  when: item.device is defined
  loop: "{{ volumes }}"

- name: Checking and registering folders
  tags: 'volumes'
  become: yes
  stat:
    path: "{{ item.mountpoint }}"
  register: directory_stats
  loop: "{{ volumes }}"

- name: Create directory
  tags: 'volumes'
  become: yes
  file:
    path: "{{ item.item.mountpoint }}"
    recurse: yes
    state: directory
  when: item.stat.exists == false
  loop: "{{ directory_stats.results }}"

- name: Attach volume to instance
  tags: 'volumes'
  become: yes
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.device }}"
    fstype: xfs
    state: mounted
  when: item.device is defined
  loop: "{{ volumes }}"
