---
# Setting up CouchDB cluster
- name: Registering nodes in cluster
  command: "curl -X POST http://{{couchdb_user_name}}:{{couchdb_password}}@{{ansible_default_ipv4.address}}:5984/_cluster_setup -H \"Content-Type:application/json\" -d '{\"action\":\"enable_cluster\", \"bind_address\":\"0.0.0.0\", \"username\":\"{{couchdb_user_name}}\", \"password\":\"{{couchdb_password}}\", \"port\":\"5984\", \"remote_node\":\"{{item}}\", \"node_count\":\"{{ansible_loop.index}}\", \"remote_current_user\":\"{{couchdb_user_name}}\", \"remote_current_password\":\"{{couchdb_password}}\"}'"
  loop: "{{ couchdb_nodes }}"
  loop_control:
    extended: yes 
    
- name: Adding nodes to cluster
  command: "curl -X POST http://{{couchdb_user_name}}:{{couchdb_password}}@{{ansible_default_ipv4.address}}:5984/_cluster_setup -H \"Content-Type:application/json\" -d '{\"action\":\"add_node\", \"host\":\"{{item}}\", \"port\":\"5984\", \"username\":\"{{couchdb_user_name}}\", \"password\":\"{{couchdb_password}}\"}'"
  loop: "{{ couchdb_nodes }}"
  loop_control:
    extended: yes 

- name: Finishing cluster setup    
  command: "curl -X POST http://{{couchdb_user_name}}:{{couchdb_password}}@{{ansible_default_ipv4.address}}:5984/_cluster_setup -H \"Content-Type:application/json\" -d '{\"action\":\"finish_cluster\"}'"

- name: Check cluster configuration
  command: "curl -X GET http://{{couchdb_user_name}}:{{couchdb_password}}@{{ansible_default_ipv4.address}}:5984/_membership"
  loop: "{{ couchdb_nodes }}"
  loop_control:
    extended: yes

- name: Create database cluster
  command: "curl -X PUT http://{{couchdb_user_name}}:{{couchdb_password}}@{{ansible_default_ipv4.address}}:5984/twitter?q=3&n=3&w=1&r=1"

- name: Check all databases
  command: "curl -X GET http://{{couchdb_user_name}}:{{couchdb_password}}@{{ansible_default_ipv4.address}}:5984/_all_dbs"
  loop: "{{ couchdb_nodes }}"
  loop_control:
    extended: yes